BEGIN;
--
-- Create model User
--
CREATE TABLE "user_user"
(
    "id"           bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "last_login"   timestamp with time zone NULL,
    "is_superuser" boolean                  NOT NULL,
    "username"     varchar(150)             NOT NULL UNIQUE,
    "first_name"   varchar(150)             NOT NULL,
    "last_name"    varchar(150)             NOT NULL,
    "is_staff"     boolean                  NOT NULL,
    "is_active"    boolean                  NOT NULL,
    "date_joined"  timestamp with time zone NOT NULL,
    "email"        varchar(255)             NOT NULL UNIQUE,
    "password"     varchar(50)              NOT NULL,
    "level"        integer                  NOT NULL
);
CREATE TABLE "user_user_groups"
(
    "id"       bigint  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id"  bigint  NOT NULL,
    "group_id" integer NOT NULL
);
CREATE TABLE "user_user_user_permissions"
(
    "id"            bigint  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id"       bigint  NOT NULL,
    "permission_id" integer NOT NULL
);
--
-- Create model AccessTable
--
CREATE TABLE "user_accesstable"
(
    "id"         bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "token"      varchar(1000)            NULL,
    "ip_address" inet                     NULL,
    "created_at" timestamp with time zone NOT NULL,
    "logout_at"  timestamp with time zone NULL,
    "status"     boolean                  NOT NULL,
    "user_id_id" bigint                   NOT NULL
);
--
-- Create model PaymentHistory
--
CREATE TABLE "user_paymenthistory"
(
    "payment_id"       uuid                     NOT NULL PRIMARY KEY,
    "time"             timestamp with time zone NOT NULL,
    "amount"           double precision         NOT NULL,
    "payment_method"   varchar(50)              NULL,
    "transaction_date" timestamp with time zone NOT NULL,
    "status"           varchar(20)              NOT NULL,
    "description"      text                     NULL,
    "payment_source"   varchar(50)              NULL,
    "user_id_id"       bigint                   NOT NULL
);
--
-- Create model TicketTable
--
CREATE TABLE "user_tickettable"
(
    "ticket_id"     uuid                     NOT NULL PRIMARY KEY,
    "priority"      integer                  NOT NULL,
    "message"       text                     NOT NULL,
    "response"      text                     NULL,
    "status"        boolean                  NOT NULL,
    "created_at"    timestamp with time zone NOT NULL,
    "response_time" timestamp with time zone NULL,
    "user_id_id"    bigint                   NOT NULL
);
--
-- Create model UserCredit
--
CREATE TABLE "user_usercredit"
(
    "id"           bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "credit"       double precision         NOT NULL,
    "gift"         integer                  NOT NULL,
    "last_payment" timestamp with time zone NOT NULL,
    "user_id_id"   bigint                   NOT NULL
);
CREATE INDEX "user_user_username_e2bdfe0c_like" ON "user_user" ("username" varchar_pattern_ops);
CREATE INDEX "user_user_email_1c6f3d1a_like" ON "user_user" ("email" varchar_pattern_ops);
ALTER TABLE "user_user_groups"
    ADD CONSTRAINT "user_user_groups_user_id_group_id_bb60391f_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "user_user_groups"
    ADD CONSTRAINT "user_user_groups_user_id_13f9a20d_fk_user_user_id" FOREIGN KEY ("user_id") REFERENCES "user_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_user_groups"
    ADD CONSTRAINT "user_user_groups_group_id_c57f13c0_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_user_groups_user_id_13f9a20d" ON "user_user_groups" ("user_id");
CREATE INDEX "user_user_groups_group_id_c57f13c0" ON "user_user_groups" ("group_id");
ALTER TABLE "user_user_user_permissions"
    ADD CONSTRAINT "user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "user_user_user_permissions"
    ADD CONSTRAINT "user_user_user_permissions_user_id_31782f58_fk_user_user_id" FOREIGN KEY ("user_id") REFERENCES "user_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_user_user_permissions"
    ADD CONSTRAINT "user_user_user_permi_permission_id_ce49d4de_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_user_user_permissions_user_id_31782f58" ON "user_user_user_permissions" ("user_id");
CREATE INDEX "user_user_user_permissions_permission_id_ce49d4de" ON "user_user_user_permissions" ("permission_id");
ALTER TABLE "user_accesstable"
    ADD CONSTRAINT "user_accesstable_user_id_id_c5be9e53_fk_user_user_id" FOREIGN KEY ("user_id_id") REFERENCES "user_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_accesstable_user_id_id_c5be9e53" ON "user_accesstable" ("user_id_id");
ALTER TABLE "user_paymenthistory"
    ADD CONSTRAINT "user_paymenthistory_user_id_id_66bb2811_fk_user_user_id" FOREIGN KEY ("user_id_id") REFERENCES "user_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_paymenthistory_user_id_id_66bb2811" ON "user_paymenthistory" ("user_id_id");
ALTER TABLE "user_tickettable"
    ADD CONSTRAINT "user_tickettable_user_id_id_75181c5b_fk_user_user_id" FOREIGN KEY ("user_id_id") REFERENCES "user_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_tickettable_user_id_id_75181c5b" ON "user_tickettable" ("user_id_id");
ALTER TABLE "user_usercredit"
    ADD CONSTRAINT "user_usercredit_user_id_id_44e727a2_fk_user_user_id" FOREIGN KEY ("user_id_id") REFERENCES "user_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_usercredit_user_id_id_44e727a2" ON "user_usercredit" ("user_id_id");
COMMIT;
