BEGIN;
--
-- Create model AboutUs
--
CREATE TABLE "home_aboutus"
(
    "id"        bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "email"     varchar(254) NOT NULL,
    "bio"       text         NOT NULL,
    "phone"     varchar(15)  NOT NULL UNIQUE,
    "address"   text         NOT NULL,
    "github"    varchar(200) NOT NULL,
    "linkedin"  varchar(200) NULL,
    "instagram" varchar(200) NULL,
    "telegram"  varchar(200) NULL
);
--
-- Create model ContactUsMessage
--
CREATE TABLE "home_contactusmessage"
(
    "id"         bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name"       varchar(100)             NOT NULL,
    "email"      varchar(254)             NOT NULL,
    "phone"      varchar(15)              NOT NULL,
    "subject"
                 varchar(100)             NULL,
    "message"    text                     NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "status"     boolean                  NOT NULL
);
--
-- Create model Pricing
--
CREATE TABLE "home_pricing"
(
    "id"             bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title"          varchar(10) NOT NULL UNIQUE,
    "description"    text        NOT NULL,
    "price"          integer     NOT NULL,
    "count"          integer     NOT NULL,
    "active_email"   integer     NOT NULL,
    "module"         integer     NOT NULL,
    "automatic_scan" integer     NOT NULL
);
--
-- Create model Team
--
CREATE TABLE "home_team"
(
    "id"          bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "full_name"   varchar(50)  NOT NULL,
    "email"       varchar(254) NOT NULL,
    "phone"       varchar(15)  NOT NULL UNIQUE,
    "nick_name"   varchar(50)  NOT NULL UNIQUE,
    "position"    varchar(50)  NOT NULL,
    "description" text         NULL,
    "image"       varchar(100) NOT NULL,
    "instagram"   varchar(200) NULL,
    "telegram"    varchar(200) NULL,
    "github"      varchar(200) NULL,
    "linkedin"    varchar(200) NULL,
    "site"        varchar(200) NULL
);
CREATE INDEX "home_aboutus_phone_63fc97a2_like" ON "home_aboutus" ("phone" varchar_pattern_ops);
CREATE INDEX "home_pricing_title_13736fe8_like" ON "home_pricing" ("title" varchar_pattern_ops);
CREATE INDEX "home_team_phone_ff6bdb72_like" ON "home_team" ("phone" varchar_pattern_ops);
CREATE INDEX "home_team_nick_name_288addfc_like" ON "home_team" ("nick_name" varchar_pattern_ops);
COMMIT;